#pragma once

#include <string>
#include <vector>
#include "llm_client.h"

namespace agent {

/**
 * A single step in a task plan.
 */
struct Step {
    int id;
    std::string description;
    // pending | in_progress | completed | failed
    std::string status = "pending";
    std::string result;
};

/**
 * A complete plan generated by the LLM.
 */
struct Plan {
    std::string overall_goal;
    std::vector<Step> steps;
};

/**
 * Result of executing a single step, used for replanning context.
 */
struct StepResult {
    int id;
    std::string description;
    std::string output;       // what the agent produced
    bool success;             // whether the step succeeded
    std::string error_message; // if failed, why
};

/**
 * TaskPlanner breaks a complex task into ordered sub-steps via the LLM.
 * The Agent then executes each step sequentially, tracking status and results.
 * If a step fails, the planner can re-plan from that point.
 */
class TaskPlanner {
public:
    explicit TaskPlanner(LLMClient& llm);

    // Generate an initial plan for the given task description.
    Plan generate_plan(const std::string& task, const std::vector<ChatMessage>& context = {});

    // Re-plan after a step failed — includes completed steps and failure reason.
    Plan replan(const std::string& original_task,
                const std::vector<StepResult>& completed_steps,
                const std::string& failure_reason);

private:
    LLMClient& llm_;

    // System prompt that instructs the LLM to produce a structured plan.
    static std::string planning_system_prompt();

    // Parse the LLM's response into a Plan struct.
    static Plan parse_plan(const std::string& raw_response);
};

} // namespace agent
